# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
# base_url: https://www.someone.com # **required!** The site's Protocol and Hostname e.g. https://blog.someone.com
base_path: '/'
title: 浪人小站
description: > #this means to ignore newlines until "nav_lists:"


nav_lists:
  - title: About
    url: /about.html

## GitHub repository (if the site is hosted by GitHub) ##
# github_repo: e.g. someone.github.io
# github_repo_tree: e.g. master

## Language & timezone ##
lang: zh #the language of your site
timezone: Asia/Shanghai

## Author & social ##
author: Richey.li
# email:  #your Email address e.g. someone@site.com
# facebook_username:  #your Facebook username
# twitter_username:  #your Twitter username
# github_username:  #your GitHub username
# googleplus_username:  #your Google+ username
# weibo_username:  #your Weibo username
# douban_username:  #your Douban username
# linkedin_username:  #your Linkedin username

## Comment system (Disqus) ##
# disqus_shortname:  #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
app_id: uNUicK9cC7Hc6BozDl3vJ1qh-gzGzoHsz
app_key: gKDmyh2M5uhQL0KMbClpyGO2
app_class: blog_view

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false